# template_validating_webhook.yaml
kind: Service
apiVersion: v1
metadata:
  name: template-webhook
  namespace: template
spec:
  selector:
    app: template-validating-webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: template
  labels:
    app: template-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-validating-webhook
  template:
    metadata:
      labels:
        app: template-validating-webhook
    spec:
      containers:
      - name: webhook
        image: 172.22.11.2:30500/template-validating-webhook:test
        imagePullPolicy: Always